# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project
#
# Aggregates the generated Foretoken CRDs for Kustomize.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/inference.foretoken.io_frontendservices.yaml
  - bases/inference.foretoken.io_modelservices.yaml
  - bases/inference.foretoken.io_modelpools.yaml
  - bases/inference.foretoken.io_modelgroups.yaml
