# This rule is not used by the project control-plane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to autoscaling.foretoken.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/managed-by: kustomize
  name: autoscaling-inferenceautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.foretoken.ai
  resources:
  - inferenceautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.foretoken.ai
  resources:
  - inferenceautoscalers/status
  verbs:
  - get
