# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

apiVersion: inference.foretoken.io/v1alpha1
kind: RuntimeCache
metadata:
  name: models
spec:
  initialSize: 10Gi
  accessMode: ReadWriteMany
  retentionPolicy: Delete
  expansion:
    mode: Automatic
    reserve: 10Gi
    maxSize: 100Gi
