//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright contributors to the Foretoken project
//
// Provides generated support code for the Foretoken API types.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingTargetStatus) DeepCopyInto(out *AutoscalingTargetStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingTargetStatus.
func (in *AutoscalingTargetStatus) DeepCopy() *AutoscalingTargetStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledParallelism) DeepCopyInto(out *CompiledParallelism) {
	*out = *in
	if in.EP != nil {
		in, out := &in.EP, &out.EP
		*out = new(ExpertParallelism)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledParallelism.
func (in *CompiledParallelism) DeepCopy() *CompiledParallelism {
	if in == nil {
		return nil
	}
	out := new(CompiledParallelism)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceLimits) DeepCopyInto(out *ComputeResourceLimits) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(ResourceQuantity)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(ResourceQuantity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceLimits.
func (in *ComputeResourceLimits) DeepCopy() *ComputeResourceLimits {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceRequests) DeepCopyInto(out *ComputeResourceRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceRequests.
func (in *ComputeResourceRequests) DeepCopy() *ComputeResourceRequests {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECProfileReference) DeepCopyInto(out *ECProfileReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECProfileReference.
func (in *ECProfileReference) DeepCopy() *ECProfileReference {
	if in == nil {
		return nil
	}
	out := new(ECProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpertParallelism) DeepCopyInto(out *ExpertParallelism) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpertParallelism.
func (in *ExpertParallelism) DeepCopy() *ExpertParallelism {
	if in == nil {
		return nil
	}
	out := new(ExpertParallelism)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendResources) DeepCopyInto(out *FrontendResources) {
	*out = *in
	out.Requests = in.Requests
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ComputeResourceLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendResources.
func (in *FrontendResources) DeepCopy() *FrontendResources {
	if in == nil {
		return nil
	}
	out := new(FrontendResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendService) DeepCopyInto(out *FrontendService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendService.
func (in *FrontendService) DeepCopy() *FrontendService {
	if in == nil {
		return nil
	}
	out := new(FrontendService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrontendService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendServiceList) DeepCopyInto(out *FrontendServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FrontendService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendServiceList.
func (in *FrontendServiceList) DeepCopy() *FrontendServiceList {
	if in == nil {
		return nil
	}
	out := new(FrontendServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrontendServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendServiceSpec) DeepCopyInto(out *FrontendServiceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Timeouts = in.Timeouts
	out.RouterPipeline = in.RouterPipeline
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendServiceSpec.
func (in *FrontendServiceSpec) DeepCopy() *FrontendServiceSpec {
	if in == nil {
		return nil
	}
	out := new(FrontendServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendServiceStatus) DeepCopyInto(out *FrontendServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendServiceStatus.
func (in *FrontendServiceStatus) DeepCopy() *FrontendServiceStatus {
	if in == nil {
		return nil
	}
	out := new(FrontendServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendTimeouts) DeepCopyInto(out *FrontendTimeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendTimeouts.
func (in *FrontendTimeouts) DeepCopy() *FrontendTimeouts {
	if in == nil {
		return nil
	}
	out := new(FrontendTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequest) DeepCopyInto(out *GPURequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequest.
func (in *GPURequest) DeepCopy() *GPURequest {
	if in == nil {
		return nil
	}
	out := new(GPURequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVCache) DeepCopyInto(out *KVCache) {
	*out = *in
	if in.Offload != nil {
		in, out := &in.Offload, &out.Offload
		*out = new(KVOffload)
		**out = **in
	}
	if in.MooncakeStore != nil {
		in, out := &in.MooncakeStore, &out.MooncakeStore
		*out = new(MooncakeStore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVCache.
func (in *KVCache) DeepCopy() *KVCache {
	if in == nil {
		return nil
	}
	out := new(KVCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVClientTemplate) DeepCopyInto(out *KVClientTemplate) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(KVDisk)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVClientTemplate.
func (in *KVClientTemplate) DeepCopy() *KVClientTemplate {
	if in == nil {
		return nil
	}
	out := new(KVClientTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVDisk) DeepCopyInto(out *KVDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVDisk.
func (in *KVDisk) DeepCopy() *KVDisk {
	if in == nil {
		return nil
	}
	out := new(KVDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVGroup) DeepCopyInto(out *KVGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVGroup.
func (in *KVGroup) DeepCopy() *KVGroup {
	if in == nil {
		return nil
	}
	out := new(KVGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVGroupClientConfig) DeepCopyInto(out *KVGroupClientConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Disk = in.Disk
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVGroupClientConfig.
func (in *KVGroupClientConfig) DeepCopy() *KVGroupClientConfig {
	if in == nil {
		return nil
	}
	out := new(KVGroupClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVGroupDisk) DeepCopyInto(out *KVGroupDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVGroupDisk.
func (in *KVGroupDisk) DeepCopy() *KVGroupDisk {
	if in == nil {
		return nil
	}
	out := new(KVGroupDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVGroupList) DeepCopyInto(out *KVGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVGroupList.
func (in *KVGroupList) DeepCopy() *KVGroupList {
	if in == nil {
		return nil
	}
	out := new(KVGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVGroupSpec) DeepCopyInto(out *KVGroupSpec) {
	*out = *in
	out.KVPoolRef = in.KVPoolRef
	in.Client.DeepCopyInto(&out.Client)
	out.Timeouts = in.Timeouts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVGroupSpec.
func (in *KVGroupSpec) DeepCopy() *KVGroupSpec {
	if in == nil {
		return nil
	}
	out := new(KVGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVGroupStatus) DeepCopyInto(out *KVGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVGroupStatus.
func (in *KVGroupStatus) DeepCopy() *KVGroupStatus {
	if in == nil {
		return nil
	}
	out := new(KVGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMasterSpec) DeepCopyInto(out *KVMasterSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotStorage)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMasterSpec.
func (in *KVMasterSpec) DeepCopy() *KVMasterSpec {
	if in == nil {
		return nil
	}
	out := new(KVMasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVOffload) DeepCopyInto(out *KVOffload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVOffload.
func (in *KVOffload) DeepCopy() *KVOffload {
	if in == nil {
		return nil
	}
	out := new(KVOffload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVPool) DeepCopyInto(out *KVPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVPool.
func (in *KVPool) DeepCopy() *KVPool {
	if in == nil {
		return nil
	}
	out := new(KVPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVPoolList) DeepCopyInto(out *KVPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVPoolList.
func (in *KVPoolList) DeepCopy() *KVPoolList {
	if in == nil {
		return nil
	}
	out := new(KVPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVPoolSpec) DeepCopyInto(out *KVPoolSpec) {
	*out = *in
	out.KVServiceRef = in.KVServiceRef
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVPoolSpec.
func (in *KVPoolSpec) DeepCopy() *KVPoolSpec {
	if in == nil {
		return nil
	}
	out := new(KVPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVPoolStatus) DeepCopyInto(out *KVPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVPoolStatus.
func (in *KVPoolStatus) DeepCopy() *KVPoolStatus {
	if in == nil {
		return nil
	}
	out := new(KVPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRequesterSpec) DeepCopyInto(out *KVRequesterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRequesterSpec.
func (in *KVRequesterSpec) DeepCopy() *KVRequesterSpec {
	if in == nil {
		return nil
	}
	out := new(KVRequesterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVResources) DeepCopyInto(out *KVResources) {
	*out = *in
	out.Requests = in.Requests
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ComputeResourceLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVResources.
func (in *KVResources) DeepCopy() *KVResources {
	if in == nil {
		return nil
	}
	out := new(KVResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVService) DeepCopyInto(out *KVService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVService.
func (in *KVService) DeepCopy() *KVService {
	if in == nil {
		return nil
	}
	out := new(KVService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVServiceBinding) DeepCopyInto(out *KVServiceBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVServiceBinding.
func (in *KVServiceBinding) DeepCopy() *KVServiceBinding {
	if in == nil {
		return nil
	}
	out := new(KVServiceBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVServiceList) DeepCopyInto(out *KVServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVServiceList.
func (in *KVServiceList) DeepCopy() *KVServiceList {
	if in == nil {
		return nil
	}
	out := new(KVServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVServiceReference) DeepCopyInto(out *KVServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVServiceReference.
func (in *KVServiceReference) DeepCopy() *KVServiceReference {
	if in == nil {
		return nil
	}
	out := new(KVServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVServiceSpec) DeepCopyInto(out *KVServiceSpec) {
	*out = *in
	in.Master.DeepCopyInto(&out.Master)
	if in.StoragePools != nil {
		in, out := &in.StoragePools, &out.StoragePools
		*out = make([]KVStoragePoolTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Timeouts = in.Timeouts
	out.Requester = in.Requester
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVServiceSpec.
func (in *KVServiceSpec) DeepCopy() *KVServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KVServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVServiceStatus) DeepCopyInto(out *KVServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Binding != nil {
		in, out := &in.Binding, &out.Binding
		*out = new(KVServiceBinding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVServiceStatus.
func (in *KVServiceStatus) DeepCopy() *KVServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KVServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVStoragePoolTemplate) DeepCopyInto(out *KVStoragePoolTemplate) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVStoragePoolTemplate.
func (in *KVStoragePoolTemplate) DeepCopy() *KVStoragePoolTemplate {
	if in == nil {
		return nil
	}
	out := new(KVStoragePoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVTimeouts) DeepCopyInto(out *KVTimeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVTimeouts.
func (in *KVTimeouts) DeepCopy() *KVTimeouts {
	if in == nil {
		return nil
	}
	out := new(KVTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedMooncakeStoreBinding) DeepCopyInto(out *ManagedMooncakeStoreBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedMooncakeStoreBinding.
func (in *ManagedMooncakeStoreBinding) DeepCopy() *ManagedMooncakeStoreBinding {
	if in == nil {
		return nil
	}
	out := new(ManagedMooncakeStoreBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelAutoscalingAdjustmentConfig) DeepCopyInto(out *ModelAutoscalingAdjustmentConfig) {
	*out = *in
	if in.MaxScaleUpGroups != nil {
		in, out := &in.MaxScaleUpGroups, &out.MaxScaleUpGroups
		*out = new(int32)
		**out = **in
	}
	if in.MaxScaleDownGroups != nil {
		in, out := &in.MaxScaleDownGroups, &out.MaxScaleDownGroups
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelAutoscalingAdjustmentConfig.
func (in *ModelAutoscalingAdjustmentConfig) DeepCopy() *ModelAutoscalingAdjustmentConfig {
	if in == nil {
		return nil
	}
	out := new(ModelAutoscalingAdjustmentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelAutoscalingConfig) DeepCopyInto(out *ModelAutoscalingConfig) {
	*out = *in
	if in.MinGroups != nil {
		in, out := &in.MinGroups, &out.MinGroups
		*out = new(int32)
		**out = **in
	}
	if in.MaxGroups != nil {
		in, out := &in.MaxGroups, &out.MaxGroups
		*out = new(int32)
		**out = **in
	}
	if in.TargetQueuePerRoutableGroup != nil {
		in, out := &in.TargetQueuePerRoutableGroup, &out.TargetQueuePerRoutableGroup
		*out = new(int64)
		**out = **in
	}
	if in.ScaleUpQueue != nil {
		in, out := &in.ScaleUpQueue, &out.ScaleUpQueue
		*out = new(int64)
		**out = **in
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(ModelAutoscalingTriggerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Adjustment != nil {
		in, out := &in.Adjustment, &out.Adjustment
		*out = new(ModelAutoscalingAdjustmentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelAutoscalingConfig.
func (in *ModelAutoscalingConfig) DeepCopy() *ModelAutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(ModelAutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelAutoscalingTriggerConfig) DeepCopyInto(out *ModelAutoscalingTriggerConfig) {
	*out = *in
	if in.LowQueuePerRoutableGroup != nil {
		in, out := &in.LowQueuePerRoutableGroup, &out.LowQueuePerRoutableGroup
		*out = new(int64)
		**out = **in
	}
	if in.HighQueuePerRoutableGroup != nil {
		in, out := &in.HighQueuePerRoutableGroup, &out.HighQueuePerRoutableGroup
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelAutoscalingTriggerConfig.
func (in *ModelAutoscalingTriggerConfig) DeepCopy() *ModelAutoscalingTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(ModelAutoscalingTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelFeatures) DeepCopyInto(out *ModelFeatures) {
	*out = *in
	if in.StructuredOutputs != nil {
		in, out := &in.StructuredOutputs, &out.StructuredOutputs
		*out = make([]StructuredOutputFormat, len(*in))
		copy(*out, *in)
	}
	if in.Multimodal != nil {
		in, out := &in.Multimodal, &out.Multimodal
		*out = make([]MultimodalModality, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelFeatures.
func (in *ModelFeatures) DeepCopy() *ModelFeatures {
	if in == nil {
		return nil
	}
	out := new(ModelFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroup) DeepCopyInto(out *ModelGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroup.
func (in *ModelGroup) DeepCopy() *ModelGroup {
	if in == nil {
		return nil
	}
	out := new(ModelGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupAccelerator) DeepCopyInto(out *ModelGroupAccelerator) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupAccelerator.
func (in *ModelGroupAccelerator) DeepCopy() *ModelGroupAccelerator {
	if in == nil {
		return nil
	}
	out := new(ModelGroupAccelerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupArtifacts) DeepCopyInto(out *ModelGroupArtifacts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupArtifacts.
func (in *ModelGroupArtifacts) DeepCopy() *ModelGroupArtifacts {
	if in == nil {
		return nil
	}
	out := new(ModelGroupArtifacts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupECRuntimeConfig) DeepCopyInto(out *ModelGroupECRuntimeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupECRuntimeConfig.
func (in *ModelGroupECRuntimeConfig) DeepCopy() *ModelGroupECRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ModelGroupECRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupKVOffloadRuntime) DeepCopyInto(out *ModelGroupKVOffloadRuntime) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupKVOffloadRuntime.
func (in *ModelGroupKVOffloadRuntime) DeepCopy() *ModelGroupKVOffloadRuntime {
	if in == nil {
		return nil
	}
	out := new(ModelGroupKVOffloadRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupKVRuntimeConfig) DeepCopyInto(out *ModelGroupKVRuntimeConfig) {
	*out = *in
	if in.Offload != nil {
		in, out := &in.Offload, &out.Offload
		*out = new(ModelGroupKVOffloadRuntime)
		**out = **in
	}
	if in.MooncakeStore != nil {
		in, out := &in.MooncakeStore, &out.MooncakeStore
		*out = new(ModelGroupMooncakeStoreRuntime)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupKVRuntimeConfig.
func (in *ModelGroupKVRuntimeConfig) DeepCopy() *ModelGroupKVRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ModelGroupKVRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupList) DeepCopyInto(out *ModelGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupList.
func (in *ModelGroupList) DeepCopy() *ModelGroupList {
	if in == nil {
		return nil
	}
	out := new(ModelGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupMooncakeStoreRuntime) DeepCopyInto(out *ModelGroupMooncakeStoreRuntime) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupMooncakeStoreRuntime.
func (in *ModelGroupMooncakeStoreRuntime) DeepCopy() *ModelGroupMooncakeStoreRuntime {
	if in == nil {
		return nil
	}
	out := new(ModelGroupMooncakeStoreRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupPDRuntimeConfig) DeepCopyInto(out *ModelGroupPDRuntimeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupPDRuntimeConfig.
func (in *ModelGroupPDRuntimeConfig) DeepCopy() *ModelGroupPDRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ModelGroupPDRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupRuntime) DeepCopyInto(out *ModelGroupRuntime) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]BackendArg, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupRuntime.
func (in *ModelGroupRuntime) DeepCopy() *ModelGroupRuntime {
	if in == nil {
		return nil
	}
	out := new(ModelGroupRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupSpec) DeepCopyInto(out *ModelGroupSpec) {
	*out = *in
	out.ModelPoolRef = in.ModelPoolRef
	out.Artifacts = in.Artifacts
	in.Runtime.DeepCopyInto(&out.Runtime)
	if in.PDRuntime != nil {
		in, out := &in.PDRuntime, &out.PDRuntime
		*out = new(ModelGroupPDRuntimeConfig)
		**out = **in
	}
	if in.ECRuntime != nil {
		in, out := &in.ECRuntime, &out.ECRuntime
		*out = new(ModelGroupECRuntimeConfig)
		**out = **in
	}
	if in.KVRuntime != nil {
		in, out := &in.KVRuntime, &out.KVRuntime
		*out = new(ModelGroupKVRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Timeouts = in.Timeouts
	in.Parallelism.DeepCopyInto(&out.Parallelism)
	if in.MaxInputTokens != nil {
		in, out := &in.MaxInputTokens, &out.MaxInputTokens
		*out = new(int32)
		**out = **in
	}
	in.Features.DeepCopyInto(&out.Features)
	in.Accelerator.DeepCopyInto(&out.Accelerator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupSpec.
func (in *ModelGroupSpec) DeepCopy() *ModelGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ModelGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGroupStatus) DeepCopyInto(out *ModelGroupStatus) {
	*out = *in
	if in.DrainStartedAt != nil {
		in, out := &in.DrainStartedAt, &out.DrainStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGroupStatus.
func (in *ModelGroupStatus) DeepCopy() *ModelGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ModelGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPool) DeepCopyInto(out *ModelPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPool.
func (in *ModelPool) DeepCopy() *ModelPool {
	if in == nil {
		return nil
	}
	out := new(ModelPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolList) DeepCopyInto(out *ModelPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolList.
func (in *ModelPoolList) DeepCopy() *ModelPoolList {
	if in == nil {
		return nil
	}
	out := new(ModelPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolSpec) DeepCopyInto(out *ModelPoolSpec) {
	*out = *in
	out.ModelServiceRef = in.ModelServiceRef
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolSpec.
func (in *ModelPoolSpec) DeepCopy() *ModelPoolSpec {
	if in == nil {
		return nil
	}
	out := new(ModelPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolStatus) DeepCopyInto(out *ModelPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolStatus.
func (in *ModelPoolStatus) DeepCopy() *ModelPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ModelPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolTemplate) DeepCopyInto(out *ModelPoolTemplate) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Parallelism.DeepCopyInto(&out.Parallelism)
	if in.MaxInputTokens != nil {
		in, out := &in.MaxInputTokens, &out.MaxInputTokens
		*out = new(int32)
		**out = **in
	}
	if in.KVCache != nil {
		in, out := &in.KVCache, &out.KVCache
		*out = new(KVCache)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(ModelFeatures)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolTemplate.
func (in *ModelPoolTemplate) DeepCopy() *ModelPoolTemplate {
	if in == nil {
		return nil
	}
	out := new(ModelPoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelResourceRequests) DeepCopyInto(out *ModelResourceRequests) {
	*out = *in
	out.ComputeResourceRequests = in.ComputeResourceRequests
	out.GPU = in.GPU
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelResourceRequests.
func (in *ModelResourceRequests) DeepCopy() *ModelResourceRequests {
	if in == nil {
		return nil
	}
	out := new(ModelResourceRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelResources) DeepCopyInto(out *ModelResources) {
	*out = *in
	out.Requests = in.Requests
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ComputeResourceLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelResources.
func (in *ModelResources) DeepCopy() *ModelResources {
	if in == nil {
		return nil
	}
	out := new(ModelResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelService) DeepCopyInto(out *ModelService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelService.
func (in *ModelService) DeepCopy() *ModelService {
	if in == nil {
		return nil
	}
	out := new(ModelService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelServiceList) DeepCopyInto(out *ModelServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelServiceList.
func (in *ModelServiceList) DeepCopy() *ModelServiceList {
	if in == nil {
		return nil
	}
	out := new(ModelServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelServiceSpec) DeepCopyInto(out *ModelServiceSpec) {
	*out = *in
	if in.InternalGenerateRequestBodyLimitBytes != nil {
		in, out := &in.InternalGenerateRequestBodyLimitBytes, &out.InternalGenerateRequestBodyLimitBytes
		*out = new(int64)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ModelResources)
		(*in).DeepCopyInto(*out)
	}
	out.Timeouts = in.Timeouts
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(ModelAutoscalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(Parallelism)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxInputTokens != nil {
		in, out := &in.MaxInputTokens, &out.MaxInputTokens
		*out = new(int32)
		**out = **in
	}
	if in.KVCache != nil {
		in, out := &in.KVCache, &out.KVCache
		*out = new(KVCache)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(ModelFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.ECProfile != nil {
		in, out := &in.ECProfile, &out.ECProfile
		*out = new(ECProfileReference)
		**out = **in
	}
	if in.ModelPools != nil {
		in, out := &in.ModelPools, &out.ModelPools
		*out = make([]ModelPoolTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]BackendArg, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelServiceSpec.
func (in *ModelServiceSpec) DeepCopy() *ModelServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ModelServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelServiceStatus) DeepCopyInto(out *ModelServiceStatus) {
	*out = *in
	if in.ServingPoolRevisions != nil {
		in, out := &in.ServingPoolRevisions, &out.ServingPoolRevisions
		*out = make([]ServingPoolRevision, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = make([]AutoscalingTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelServiceStatus.
func (in *ModelServiceStatus) DeepCopy() *ModelServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ModelServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelTimeouts) DeepCopyInto(out *ModelTimeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelTimeouts.
func (in *ModelTimeouts) DeepCopy() *ModelTimeouts {
	if in == nil {
		return nil
	}
	out := new(ModelTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MooncakeStore) DeepCopyInto(out *MooncakeStore) {
	*out = *in
	if in.KVServiceRef != nil {
		in, out := &in.KVServiceRef, &out.KVServiceRef
		*out = new(KVServiceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MooncakeStore.
func (in *MooncakeStore) DeepCopy() *MooncakeStore {
	if in == nil {
		return nil
	}
	out := new(MooncakeStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedKVCache) DeepCopyInto(out *NormalizedKVCache) {
	*out = *in
	if in.Offload != nil {
		in, out := &in.Offload, &out.Offload
		*out = new(KVOffload)
		**out = **in
	}
	if in.MooncakeStore != nil {
		in, out := &in.MooncakeStore, &out.MooncakeStore
		*out = new(NormalizedMooncakeStore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedKVCache.
func (in *NormalizedKVCache) DeepCopy() *NormalizedKVCache {
	if in == nil {
		return nil
	}
	out := new(NormalizedKVCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedKVPoolTemplate) DeepCopyInto(out *NormalizedKVPoolTemplate) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedKVPoolTemplate.
func (in *NormalizedKVPoolTemplate) DeepCopy() *NormalizedKVPoolTemplate {
	if in == nil {
		return nil
	}
	out := new(NormalizedKVPoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedMooncakeStore) DeepCopyInto(out *NormalizedMooncakeStore) {
	*out = *in
	if in.ManagedBinding != nil {
		in, out := &in.ManagedBinding, &out.ManagedBinding
		*out = new(ManagedMooncakeStoreBinding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedMooncakeStore.
func (in *NormalizedMooncakeStore) DeepCopy() *NormalizedMooncakeStore {
	if in == nil {
		return nil
	}
	out := new(NormalizedMooncakeStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedPoolTemplate) DeepCopyInto(out *NormalizedPoolTemplate) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Parallelism.DeepCopyInto(&out.Parallelism)
	if in.MaxInputTokens != nil {
		in, out := &in.MaxInputTokens, &out.MaxInputTokens
		*out = new(int32)
		**out = **in
	}
	out.Timeouts = in.Timeouts
	if in.KVCache != nil {
		in, out := &in.KVCache, &out.KVCache
		*out = new(NormalizedKVCache)
		(*in).DeepCopyInto(*out)
	}
	in.Features.DeepCopyInto(&out.Features)
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]BackendArg, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedPoolTemplate.
func (in *NormalizedPoolTemplate) DeepCopy() *NormalizedPoolTemplate {
	if in == nil {
		return nil
	}
	out := new(NormalizedPoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parallelism) DeepCopyInto(out *Parallelism) {
	*out = *in
	if in.DP != nil {
		in, out := &in.DP, &out.DP
		*out = new(int32)
		**out = **in
	}
	if in.EP != nil {
		in, out := &in.EP, &out.EP
		*out = new(ExpertParallelism)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parallelism.
func (in *Parallelism) DeepCopy() *Parallelism {
	if in == nil {
		return nil
	}
	out := new(Parallelism)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterPipeline) DeepCopyInto(out *RouterPipeline) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterPipeline.
func (in *RouterPipeline) DeepCopy() *RouterPipeline {
	if in == nil {
		return nil
	}
	out := new(RouterPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingPoolRevision) DeepCopyInto(out *ServingPoolRevision) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingPoolRevision.
func (in *ServingPoolRevision) DeepCopy() *ServingPoolRevision {
	if in == nil {
		return nil
	}
	out := new(ServingPoolRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotStorage) DeepCopyInto(out *SnapshotStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotStorage.
func (in *SnapshotStorage) DeepCopy() *SnapshotStorage {
	if in == nil {
		return nil
	}
	out := new(SnapshotStorage)
	in.DeepCopyInto(out)
	return out
}
