# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

apiVersion: inference.foretoken.io/v1alpha1
kind: ModelService
metadata:
  name: quickstart-qwen3-0.6b
spec:
  profiling:
    engine: nsight
