# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: foretoken-nvidia-gpu-dashboard
    grafana_dashboard: "1"
configMapGenerator:
  - name: foretoken-nvidia-gpu-dashboard
    files:
      - foretoken-nvidia-gpu-dashboard.json=dashboards/foretoken-nvidia-gpu-dashboard.json
