---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-autoscaling-foretoken-ai-v1alpha1-inferenceautoscaler
  failurePolicy: Fail
  name: minferenceautoscaler-v1alpha1.kb.io
  rules:
  - apiGroups:
    - autoscaling.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferenceautoscalers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-orchestration-foretoken-ai-v1alpha1-inferencegroup
  failurePolicy: Fail
  name: minferencegroup-v1alpha1.kb.io
  rules:
  - apiGroups:
    - orchestration.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferencegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-orchestration-foretoken-ai-v1alpha1-inferencepool
  failurePolicy: Fail
  name: minferencepool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - orchestration.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferencepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-orchestration-foretoken-ai-v1alpha1-kvcache
  failurePolicy: Fail
  name: mkvcache-v1alpha1.kb.io
  rules:
  - apiGroups:
    - orchestration.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kvcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-model-foretoken-ai-v1alpha1-modelservice
  failurePolicy: Fail
  name: mmodelservice-v1alpha1.kb.io
  rules:
  - apiGroups:
    - model.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modelservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gateway-foretoken-ai-v1alpha1-routingprofile
  failurePolicy: Fail
  name: mroutingprofile-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gateway.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routingprofiles
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-autoscaling-foretoken-ai-v1alpha1-inferenceautoscaler
  failurePolicy: Fail
  name: vinferenceautoscaler-v1alpha1.kb.io
  rules:
  - apiGroups:
    - autoscaling.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferenceautoscalers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-orchestration-foretoken-ai-v1alpha1-inferencegroup
  failurePolicy: Fail
  name: vinferencegroup-v1alpha1.kb.io
  rules:
  - apiGroups:
    - orchestration.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferencegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-orchestration-foretoken-ai-v1alpha1-inferencepool
  failurePolicy: Fail
  name: vinferencepool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - orchestration.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferencepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-orchestration-foretoken-ai-v1alpha1-kvcache
  failurePolicy: Fail
  name: vkvcache-v1alpha1.kb.io
  rules:
  - apiGroups:
    - orchestration.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kvcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-model-foretoken-ai-v1alpha1-modelservice
  failurePolicy: Fail
  name: vmodelservice-v1alpha1.kb.io
  rules:
  - apiGroups:
    - model.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modelservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-foretoken-ai-v1alpha1-routingprofile
  failurePolicy: Fail
  name: vroutingprofile-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gateway.foretoken.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routingprofiles
  sideEffects: None
