# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

# Select the ServiceMonitors created by the Foretoken platform release.
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        app.kubernetes.io/name: foretoken-control-plane
    serviceMonitorNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: foretoken-platform
    ruleSelectorNilUsesHelmValues: false
    ruleSelector:
      matchLabels:
        app.kubernetes.io/name: foretoken-control-plane
    ruleNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: foretoken-platform
