# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

[package]
name = "foretoken-kv-indexer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22.1"
blake3 = "1.8.2"
foretoken-router = { path = "../router" }
foretoken-model-protocol = { path = "../../../model-protocol" }
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
axum.workspace = true
vllm-llm.workspace = true
