# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

[package]
name = "foretoken-tracing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http-body = "1.0.1"
opentelemetry = { version = "0.32.0", default-features = false, features = ["trace"] }
opentelemetry_sdk = { version = "0.32.0", default-features = false, features = ["trace"] }
opentelemetry-otlp = { version = "0.32.0", default-features = false, features = ["trace", "http-proto", "reqwest-blocking-client", "reqwest-rustls"] }
tracing.workspace = true
tracing-opentelemetry = { version = "0.33.0", default-features = false }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
