# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project
#
# Foretoken Quick Start deployment entrypoint, which deploys both the model and frontend services.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yaml
  - model.yaml
